### ISSUE TITLE
Vet appointments Kanban setup

### ISSUE THREAD

**Issue by rskinnerc** [rskinnerc/vet-appointments-rails#6]
We have created the [Kanban board](https://github.com/users/rskinnerc/projects/9/views/1) for our Final Capstone Project: Vets Appointments

We are a group of 3 people:
@rskinnerc 
@mistermaxis
@AlejandroNeira98 
@jrosario19 

![image](https://user-images.githubusercontent.com/26911718/190231668-b696de99-c1d8-47bc-b5ff-72ec1a25a420.png)

**Comment by mcrd25** [comment]
Hi Team, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


## Suggested changes
- You have most requirements down, however, one of your team members have not been assigned any tasks (@denscholar) is there a reason for this
- [OPTIONAL] I am not here to tell you how long something would take, but maybe some of these tasks are underestimated slightly. Especially front-end aspects (getting to look close to design may take a bit of time)
- [OPTIONAL] You can consider getting more detailed with your issues, like what API endpoints are you adding
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by rskinnerc** [comment]
Hello @mcrd25, thank you for your feedback.

Dennis didn't have any assigned issues/tasks because he seemed unable to connect during the first planning days. So we couldn't invite him to the repository.

Anyway, as of today, we realized he was dropped from our Final Capstone Group, so we should be good to go with the assigned tasks among us.
Thank you very much.

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  


Good luck! 🎉 


Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**Comment by rskinnerc** [comment]
Dear reviewer, please be aware we have added @jrosario19 to our project and assigned some tasks. He was moved to our group by the Student Success team.

Thank you very much.
